dist: bionic
language: go
go:
  - 1.13.x
  - master
env:
  - GO111MODULE=on
before_script:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman tree
script:
  - sudo podman pull oneinfra/containerd:latest
  - go install -mod=vendor ./...
  - sudo podman ps -a
  - sudo podman images
  - sudo ${GOPATH}/bin/oi-local-cluster
  - sudo podman ps -a
  - sudo podman images
  - sudo tree /tmp/oneinfra-cluster-test
