dist: bionic
language: go
go:
  - 1.13.x
  - master
env:
  - GO111MODULE=on
before_script:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman tree
script:
  - sudo mkdir -p /tmp/cluster-test/node-0
  - sudo podman run -d --privileged -v /cluster-test/node-0:/var/run/containerd --name test-node-0 docker.io/oneinfra/containerd:latest
  # - go install -mod=vendor ./...
  # - sudo ${GOPATH}/bin/oi-local-cluster
  # - sudo tree /tmp/oneinfra-cluster-test
