language: go

go:
  - 1.13.x
  - master

env:
  - GO111MODULE=on

before_script:
  - add-apt-repository -y ppa:projectatomic/ppa
  - apt-get update -qq
  - apt-get install -qq -y software-properties-common podman

script:
  - go version
  - go install -mod=vendor ./...
  - oi-local-cluster
  - tree /tmp/oneinfra-cluster-test
