dist: xenial
language: go
go: 1.11.x
env:
  - GO111MODULE=on
install: true
before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman
deploy:
  - provider: script
    script: go -mod=vendor install ./...
  - provider: script
    script: oi-local-cluster
  - provider: script
    script: tree /tmp/oneinfra-cluster-test
