dist: xenial
before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman
deploy:
  - provider: script
    script: go install ./...
  - provider: script
    script: oi-local-cluster
  - provider: script
    script: tree /tmp/oneinfra-cluster-test
