jobs:
  include:
    - stage: build
      name: build
      dist: bionic
      language: minimal
      script:
        - make pull-builder
        - make
    - stage: test
      name: unit and integration tests
      dist: bionic
      language: minimal
      script:
        - make pull-builder
        - make test
    - name: e2e tests with local CRI endpoints
      dist: bionic
      language: minimal
      script:
        - make deps
        - make e2e
      env: KUBERNETES_VERSION=1.17.4 CRI_TOOLS_VERSION=1.17.0
    - name: e2e tests with remote CRI endpoints
      dist: bionic
      language: minimal
      script:
        - make deps
        - make e2e-remote
      env: KUBERNETES_VERSION=1.17.4 CRI_TOOLS_VERSION=1.17.0
