dist: bionic
services:
  - docker
language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on
before_script:
  - docker pull oneinfra/containerd:latest
script:
  - GOFLAGS="-mod=vendor" make oi oi-local-cluster
  - oi-local-cluster cluster create | oi cluster inject --name test | oi node inject --name test --cluster test | tee cluster.txt | oi reconcile
