dist: bionic
language: go
go:
  - 1.13.x
  - master
env:
  - CNI_VERSION="v0.8.5" GO111MODULE=on
before_script:
  # podman
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman tree
  # CNI
  - curl -sSL --retry 5 --output /tmp/cni.tgz "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-amd64-${CNI_VERSION}.tgz"
  - mkdir -p /opt/cni/bin
  - tar -C /opt/cni/bin -xzf /tmp/cni.tgz
  - rm -f /tmp/cni.tgz
script:
  - sudo mkdir -p /tmp/cluster-test/node-0
  - sudo podman run -d --privileged -v /tmp/cluster-test/node-0:/var/run/containerd --name test-node-0 docker.io/oneinfra/containerd:latest
  # - go install -mod=vendor ./...
  # - sudo ${GOPATH}/bin/oi-local-cluster
  # - sudo tree /tmp/oneinfra-cluster-test
