variables:
  CI: "1"

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: make pull-builder
  - bash: make
- job: unit_and_integration_tests
  displayName: unit and integration tests
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: make pull-builder
  - bash: make test
- job: e2e_tests_with_local_cri_endpoints
  displayName: e2e tests with local CRI endpoints
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: make deps
  - bash: make e2e
- job: e2e_tests_with_remote_cri_endpoints
  displayName: e2e tests with remote CRI endpoints
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: make deps
  - bash: make e2e-remote
