version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
          GOFLAGS: "-mod=vendor"
    working_directory: /go/src/github.com/oneinfra/oneinfra
    steps:
      - checkout
      - run: sudo make test-deps
      - run: make test
