version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make pull-builder
      - run: make
  unit and integration tests:
    machine: true
    steps:
      - checkout
      - run: make pull-builder
      - run: make test
  e2e tests with local CRI endpoints:
    machine: true
    steps:
      - checkout
      - run: make deps
      - run: make e2e
  e2e tests with remote CRI endpoints:
    machine: true
    steps:
      - checkout
      - run: make deps
      - run: make e2e-remote
workflows:
  version: 2
  test:
    jobs:
      - build
      - unit and integration tests
      - e2e tests with local CRI endpoints
      - e2e tests with remote CRI endpoints
