version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/oneinfra/oneinfra
    steps:
      - checkout
      - run: sudo make test-deps
      - run:
          name: Run tests
          environment:
            GO111MODULE: "on"
            GOFLAGS: "-mod=vendor"
          command: make test
