version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"
      GOFLAGS: "-mod=vendor"
    working_directory: /go/src/github.com/oneinfra/oneinfra
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-pkg-cache
      - run: sudo make test-deps
      - run: make test
      - save_cache:
          key: v2-pkg-cache
          paths:
            - "/go/pkg"
            - "/usr/local/kubebuilder"
