version: 2
jobs:
  unit and integration tests:
    machine: true
    steps:
      - checkout
      - run: make pull-builder
      - run: make test
  e2e tests:
    machine: true
    steps:
      - checkout
      - run: make pull
      - run: make kubectl
      - run: make e2e
workflows:
  version: 2
  test:
    jobs:
      - unit and integration tests
      - e2e tests
