# permissions for end users to view components.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: component-viewer-role
rules:
- apiGroups:
  - cluster.oneinfra.ereslibre.es
  resources:
  - components
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.oneinfra.ereslibre.es
  resources:
  - components/status
  verbs:
  - get
