# permissions for end users to view hypervisors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypervisor-viewer-role
rules:
- apiGroups:
  - infra.oneinfra.ereslibre.es
  resources:
  - hypervisors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.oneinfra.ereslibre.es
  resources:
  - hypervisors/status
  verbs:
  - get
