
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.oneinfra.ereslibre.es
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.oneinfra.ereslibre.es
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.oneinfra.ereslibre.es
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.oneinfra.ereslibre.es
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.oneinfra.ereslibre.es
  resources:
  - hypervisors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.oneinfra.ereslibre.es
  resources:
  - hypervisors/status
  verbs:
  - get
  - patch
  - update
